# Generated by Django 4.2.2 on 2023-06-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='id',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
