# Generated by Django 4.2.2 on 2023-06-27 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0002_remove_receipt_id_alter_receipt_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
