# Generated by Django 4.2.2 on 2023-06-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipt', '0003_alter_receipt_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
